version: "3.8"
services:
  # grpcserver:
  #   container_name: "grpcserver"
  #   build: ./grpcserver
  #   environment:
  #     - RPC_SERVER_PORT=50000    
  #   expose:
  #     - "50000"
  #   networks:
  #     trakcom:
  #       ipv4_address: 172.16.239.200
  #   restart: always

  unitclient:
    container_name: "unitclient"
    build: ./unitclient
    environment:
      - RPC_SERVER_URL=host.docker.internal:49999
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    networks:
      trakcom:
        ipv4_address: 172.16.239.100
    ports:
      - "9000:80"

  uvicornclient:
    container_name: "uvicornclient"
    build: ./uvicornclient
    environment:
      - RPC_SERVER_URL=host.docker.internal:49999
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    networks:
      trakcom:
        ipv4_address: 172.16.239.101
    ports:
      - "9100:80"

networks:
  trakcom:
    ipam:
      config:
        - subnet: "172.16.239.0/24"
